### ISSUE TITLE
Can you just send the builded apk to me?

### ISSUE THREAD

**Issue by windrises** [GehenHe/Recognize-Face-on-Android#2]
I have failed many times to build the project. And in the directory :"tensorflow\examples\Face_Recognition\gradleBuild\outputs\apk\", there are tow apks that you have builded. But after I install the apk you leaved, I cann't open it. The whole screen keeps white for several seconds and the app just shut down. I guess the apks you leaved may has some bugs.
So, could you rebuild the project and send the builded apk to me? My E-mail address is wind_rises@163.com.
Thanks a lot!

**Comment by GehenHe** [comment]
Your device should support google play services anyway. And the apk is sent to your email which goes smoothly on my mobile
